import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { Activity, Apple, Bell, BookOpen, CalendarDays, Check, ChevronRight, CircleDollarSign, Coins, Dumbbell, Flame, Footprints, HeartPulse, Home, LayoutGrid, Menu, Moon, MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TrendingDown, Trophy, User, Wallet, X, Zap } from 'lucide-react';
import type { CustomGoal, DashboardData, Entry, Preferences } from './types';

const API='/api';
const defaultPreferences:Preferences={profile:{name:'',email:'',age:'',height:'',weight:''},targets:{calories:2200,protein:140,water:2.5,steps:10000},settings:{notifications:true,weekly:true,penalties:false,dark:true},customGoals:[],onboardingComplete:false};
const pageFromPath=()=>{const value=window.location.pathname.slice(1).toLowerCase();return ({overview:'Overview',journal:'Journal',progress:'Progress',goals:'Goals',settings:'Settings',profile:'Profile'} as Record<string,string>)[value]||'Today'};
const fallback:DashboardData={user:{name:'Alex Morgan',xp:2780,coins:625,level:12,nextLevelXp:3000,streak:7},today:{date:new Date().toISOString().slice(0,10),weight:74.2,calories:1280,protein:86,water:1.8,sleep:7.4,steps:6842,mood:8,energy:7,stress:3,workoutMinutes:45,notes:'',habits:{water:false,vegetables:true,teeth:true,hygiene:true,sleep:true,learn:true}},history:[74.8,74.6,74.7,74.3,74.4,74.1,74.2].map((weight,i)=>({date:`2026-06-${23+i}`,weight,calories:1900+i*50,protein:110+i*5,water:2+i*.1,sleep:6.5+i*.15,steps:6500+i*700,mood:7,energy:7,stress:3,workoutMinutes:i%2?50:0,notes:'',habits:{}})),notifications:[{id:1,title:'New personal best',message:'You hit a 7-day logging streak. Keep it alive!',type:'streak',isRead:false,createdAt:new Date().toISOString()},{id:2,title:'Protein is on track',message:'Only 54g left to reach today’s goal.',type:'success',isRead:false,createdAt:new Date().toISOString()}],goals:[{id:1,title:'10,000 daily steps',progress:6842,target:10000,color:'#d8ff4f'},{id:2,title:'Protein goal',progress:86,target:140,color:'#6fe2c1'},{id:3,title:'8 hours of sleep',progress:7.4,target:8,color:'#a88bfa'}]};

const nav=[['Today',Home],['Overview',LayoutGrid],['Journal',BookOpen],['Progress',Activity],['Goals',Target]] as const;
const habitInfo:{key:string;title:string;sub:string;icon:any;color:string}[]=[
  {key:'water',title:'Hydration goal',sub:'1.8 of 2.5 liters',icon:Zap,color:'#63d9ff'},
  {key:'vegetables',title:'Fruits & veggies',sub:'Five colorful servings',icon:Apple,color:'#d8ff4f'},
  {key:'teeth',title:'Brush teeth',sub:'Morning & evening',icon:Sparkles,color:'#f7c76c'},
  {key:'hygiene',title:'Personal care',sub:'Daily routine',icon:HeartPulse,color:'#ff8d9e'},
  {key:'sleep',title:'Sleep on time',sub:'Before 11:30 PM',icon:Moon,color:'#a88bfa'},
  {key:'learn',title:'Learn something',sub:'At least 20 minutes',icon:BookOpen,color:'#6fe2c1'}
];

function Ring({value,color='#d8ff4f',size=80,children}:{value:number;color?:string;size?:number;children?:any}){return <div className="ring" style={{width:size,height:size,background:`conic-gradient(${color} ${Math.min(100,value)*3.6}deg,rgba(255,255,255,.07) 0)`}}><div>{children}</div></div>}
function Progress({value,color='#d8ff4f'}:{value:number;color?:string}){return <div className="progress"><motion.i initial={{width:0}} animate={{width:`${Math.min(100,value)}%`}} transition={{duration:.8}} style={{background:color}}/></div>}
function MiniStat({icon:Icon,label,value,sub,color}:{icon:any;label:string;value:string;sub:string;color:string}){return <motion.div className="mini-stat card" whileHover={{y:-3}}><div className="stat-icon" style={{color,background:`${color}18`}}><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></motion.div>}

export default function App(){
  const [data,setData]=useState<DashboardData>(fallback); const [active,setActive]=useState(pageFromPath); const [modal,setModal]=useState(false); const [bell,setBell]=useState(false); const [menu,setMenu]=useState(false); const [saved,setSaved]=useState(false); const [preferences,setPreferences]=useState<Preferences|null>(null);
  useEffect(()=>{const onBack=()=>setActive(pageFromPath());window.addEventListener('popstate',onBack);return()=>window.removeEventListener('popstate',onBack)},[]);
  useEffect(()=>{(async()=>{try{let token=localStorage.getItem('dlt-token');if(!token){const visitorId=crypto.randomUUID();const a=await fetch(`${API}/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'New user',email:`${visitorId}@daylight.local`,password:crypto.randomUUID()})}).then(r=>r.json());token=a.token;localStorage.setItem('dlt-token',String(token))}const headers={Authorization:`Bearer ${token!}`};const [d,p]=await Promise.all([fetch(`${API}/dashboard`,{headers}).then(r=>r.json()),fetch(`${API}/preferences`,{headers}).then(r=>r.json())]);setData({...d,user:{...d.user,name:p.profile?.name||d.user.name}});setPreferences({...defaultPreferences,...p})}catch{setPreferences(defaultPreferences)}})()},[]);
  const toggleHabit=(key:string)=>setData(d=>({...d,today:{...d.today,habits:{...d.today.habits,[key]:!d.today.habits[key]}}}));
  const done=Object.values(data.today.habits||{}).filter(Boolean).length; const habitPct=Math.round(done/habitInfo.length*100);
  const chart=data.history.map((x,i)=>({...x,day:['M','T','W','T','F','S','S'][i]}));
  const saveEntry=async(entry:Entry)=>{setData(d=>({...d,today:entry}));setModal(false);setSaved(true);setTimeout(()=>setSaved(false),2400);try{await fetch(`${API}/entries`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify(entry)})}catch{}};
  const showSaved=()=>{setSaved(true);setTimeout(()=>setSaved(false),2400)};
  const savePreferences=async(next:Preferences)=>{setPreferences(next);if(next.profile.name)setData(d=>({...d,user:{...d.user,name:next.profile.name}}));showSaved();try{await fetch(`${API}/preferences`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify(next)})}catch{}};
  const go=(page:string)=>{setActive(page);setMenu(false);const path=page==='Today'?'/':`/${page.toLowerCase()}`;if(window.location.pathname!==path)window.history.pushState({},'',path);window.scrollTo({top:0,behavior:'smooth'})};
  return <div className="app-shell">
    <aside className={menu?'sidebar open':'sidebar'}><div className="brand" onClick={()=>go('Today')}><div className="brand-mark"><Check size={18}/></div><b>daylight</b><button className="mobile-x" onClick={(e)=>{e.stopPropagation();setMenu(false)}}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>go(n)}><I size={19}/><span>{n}</span>{active===n&&<i/>}</button>)}</nav><div className="sidebar-bottom"><div className="upgrade"><Sparkles size={20}/><b>Unlock your best</b><p>Go Pro for deeper insights.</p><button onClick={()=>go('Settings')}>Explore Daylight Pro</button></div><button className={active==='Settings'?'active':''} onClick={()=>go('Settings')}><Settings size={19}/>Settings</button><button className={active==='Profile'?'active':''} onClick={()=>go('Profile')}><User size={19}/>Profile</button></div></aside>
    <main>
      <header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Search your day..."/><kbd>⌘ K</kbd></div><div className="header-actions"><div className="streak-pill"><Flame size={17}/><b>{data.user.streak}</b><span>day streak</span></div><button className="icon-btn" aria-label="Notifications" onClick={()=>setBell(!bell)}><Bell size={20}/><i/></button><button className="avatar" aria-label="Open profile" onClick={()=>go('Profile')}>AM</button></div></header>
      <div className="content">
        {active==='Today'?<>
        <section className="welcome"><div><p className="eyebrow">SUNDAY, JUNE 29</p><h1>Good evening, <em>{data.user.name.split(' ')[0]}.</em></h1><p>Your momentum is looking good. Let’s finish the day strong.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={19}/> Log today</button></section>
        <section className="level card"><div className="level-badge"><Trophy size={22}/><b>{data.user.level}</b></div><div className="level-copy"><div><b>Level {data.user.level} · Momentum Maker</b><span>{data.user.xp.toLocaleString()} / {data.user.nextLevelXp.toLocaleString()} XP</span></div><Progress value={data.user.xp/data.user.nextLevelXp*100}/><small><Zap size={13}/> 220 XP until Level {data.user.level+1}</small></div><div className="coin-box"><Coins size={20}/><div><b>{data.user.coins}</b><span>coins</span></div><ChevronRight size={18}/></div></section>
        <section className="section-head"><div><h2>Today at a glance</h2><p>Your key metrics, all in one place.</p></div><button onClick={()=>go('Overview')}>View details <ChevronRight size={15}/></button></section>
        <section className="stats-grid"><MiniStat icon={Footprints} label="Steps" value={data.today.steps.toLocaleString()} sub="68% of 10k goal" color="#d8ff4f"/><MiniStat icon={Dumbbell} label="Active time" value={`${data.today.workoutMinutes} min`} sub="+12% from last week" color="#6fe2c1"/><MiniStat icon={Moon} label="Sleep" value={`${data.today.sleep} hrs`} sub="Quality · Great" color="#a88bfa"/><MiniStat icon={HeartPulse} label="Mood" value={`${data.today.mood}/10`} sub="Feeling focused" color="#ff8d9e"/></section>
        <section className="main-grid">
          <div className="left-column">
            <div className="card nutrition"><div className="card-title"><div><h3>Daily fuel</h3><p>Nutrition progress for today</p></div><button><MoreHorizontal/></button></div><div className="nutrition-body"><Ring value={data.today.calories/2200*100} size={134}><b>{data.today.calories.toLocaleString()}</b><span>of 2,200 kcal</span></Ring><div className="macros"><div><span><i style={{background:'#d8ff4f'}}/>Protein <b>{data.today.protein} / 140g</b></span><Progress value={data.today.protein/140*100}/></div><div><span><i style={{background:'#f7c76c'}}/>Carbs <b>142 / 230g</b></span><Progress value={62} color="#f7c76c"/></div><div><span><i style={{background:'#ff8d9e'}}/>Fat <b>48 / 73g</b></span><Progress value={66} color="#ff8d9e"/></div></div></div><div className="insight"><Sparkles size={18}/><div><b>Small win available</b><span>Add a protein-rich snack to close the gap.</span></div><ChevronRight size={18}/></div></div>
            <div className="card habits"><div className="card-title"><div><h3>Daily rhythm</h3><p>{done} of {habitInfo.length} habits completed</p></div><Ring value={habitPct} size={52}><b>{habitPct}%</b></Ring></div><div className="habit-list">{habitInfo.map(({key,title,sub,icon:Icon,color})=><motion.button whileTap={{scale:.98}} key={key} onClick={()=>toggleHabit(key)} className={data.today.habits?.[key]?'done':''}><span className="habit-icon" style={{color,background:`${color}13`}}><Icon size={18}/></span><span><b>{title}</b><small>{sub}</small></span><i>{data.today.habits?.[key]&&<Check size={15}/>}</i></motion.button>)}</div></div>
          </div>
          <div className="right-column">
            <div className="card weight"><div className="card-title"><div><h3>Weight trend</h3><p>Last 7 days</p></div><span className="down"><TrendingDown size={15}/> 0.6 kg</span></div><div className="weight-value"><b>{data.today.weight}</b><span>kg</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:4,right:4,top:8,bottom:0}}><defs><linearGradient id="weight" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8ff4f" stopOpacity=".28"/><stop offset="1" stopColor="#d8ff4f" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#6f7781',fontSize:11}}/><Tooltip contentStyle={{background:'#151a20',border:'1px solid #30363d',borderRadius:10}}/><Area type="monotone" dataKey="weight" stroke="#d8ff4f" strokeWidth={2.5} fill="url(#weight)"/></AreaChart></ResponsiveContainer></div></div>
            <div className="card goals"><div className="card-title"><div><h3>Today’s goals</h3><p>Keep moving forward</p></div><button aria-label="Open goals" onClick={()=>go('Goals')}><Plus size={18}/></button></div>{data.goals.map(g=><div className="goal" key={g.id}><div><span>{g.title}</span><b>{Math.round(g.progress/g.target*100)}%</b></div><Progress value={g.progress/g.target*100} color={g.color}/><small>{g.progress.toLocaleString()} of {g.target.toLocaleString()}</small></div>)}</div>
            <div className="card reflection"><div className="quote">“</div><h3>One thought for today</h3><p>What’s one thing you did today that your future self will thank you for?</p><button onClick={()=>setModal(true)}>Write a reflection <ChevronRight size={16}/></button></div>
          </div>
        </section>
        </>:<FeaturePage active={active} data={data} preferences={preferences||defaultPreferences} savePreferences={savePreferences} openLog={()=>setModal(true)} notify={showSaved}/>} 
      </div>
      <nav className="mobile-nav">{nav.slice(0,4).map(([n,I])=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I size={20}/><span>{n}</span></button>)}<button onClick={()=>setMenu(true)}><Menu size={20}/><span>More</span></button></nav>
    </main>
    <AnimatePresence>{bell&&<NotificationPanel items={data.notifications} close={()=>setBell(false)}/>}</AnimatePresence>
    <AnimatePresence>{modal&&<LogModal entry={data.today} close={()=>setModal(false)} save={saveEntry}/>}</AnimatePresence>
    <AnimatePresence>{preferences&&!preferences.onboardingComplete&&<OnboardingModal initial={preferences} complete={savePreferences}/>}</AnimatePresence>
    <AnimatePresence>{saved&&<motion.div className="toast" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}}><span><Check size={16}/></span><div><b>Changes saved</b><small>Your updates are safely recorded.</small></div></motion.div>}</AnimatePresence>
  </div>
}

function FeaturePage({active,data,preferences,savePreferences,openLog,notify}:{active:string;data:DashboardData;preferences:Preferences;savePreferences:(p:Preferences)=>void;openLog:()=>void;notify:()=>void}){
  const [settings,setSettings]=useState(preferences.settings);
  const [targets,setTargets]=useState(preferences.targets);
  const [profile,setProfile]=useState(preferences.profile);
  const [showGoalForm,setShowGoalForm]=useState(false);
  const [goalDraft,setGoalDraft]=useState({title:'',target:1,unit:'times',dueDate:''});
  const toggle=(key:keyof typeof settings)=>setSettings(s=>({...s,[key]:!s[key]}));
  const persist=()=>savePreferences({...preferences,settings,targets,profile});
  const addGoal=()=>{if(!goalDraft.title.trim())return;const goal:CustomGoal={id:crypto.randomUUID(),title:goalDraft.title.trim(),target:Number(goalDraft.target)||1,progress:0,unit:goalDraft.unit||'times',dueDate:goalDraft.dueDate,completed:false};savePreferences({...preferences,settings,targets,profile,customGoals:[...preferences.customGoals,goal]});setGoalDraft({title:'',target:1,unit:'times',dueDate:''});setShowGoalForm(false)};
  const pageIntro:Record<string,[string,string]>={
    Overview:['Your overview','The bigger picture across health, habits, and momentum.'],
    Journal:['Journal','A quiet place to reflect, notice patterns, and reset.'],
    Progress:['Your progress','Small choices, compounding in the right direction.'],
    Goals:['Goals','Turn intention into a plan you can actually finish.'],
    Settings:['Settings','Make Daylight work the way you do.'],
    Profile:['Your profile','Manage your identity and personal targets.']
  };
  const [title,subtitle]=pageIntro[active]||['Daylight','Your life, in focus.'];
  const average=(key:keyof Entry)=>Math.round(data.history.reduce((sum,e)=>sum+Number(e[key]||0),0)/Math.max(1,data.history.length)*10)/10;
  return <motion.div className="feature-page" key={active} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>
    <section className="page-hero"><div><p className="eyebrow">DAYLIGHT / {active.toUpperCase()}</p><h1>{title}</h1><p>{subtitle}</p></div>{active==='Journal'&&<button className="primary" onClick={openLog}><Plus size={18}/>New entry</button>}{active==='Goals'&&<button className="primary" onClick={()=>setShowGoalForm(v=>!v)}><Plus size={18}/>Add goal</button>}</section>
    {active==='Overview'&&<>
      <section className="stats-grid page-stats"><MiniStat icon={Footprints} label="Average steps" value={average('steps').toLocaleString()} sub="Last 7 days" color="#d8ff4f"/><MiniStat icon={Moon} label="Average sleep" value={`${average('sleep')} hrs`} sub="Healthy range" color="#a88bfa"/><MiniStat icon={HeartPulse} label="Average mood" value={`${average('mood')}/10`} sub="Stable this week" color="#ff8d9e"/><MiniStat icon={Dumbbell} label="Training" value="4 days" sub="185 active minutes" color="#6fe2c1"/></section>
      <section className="wide-grid"><div className="card page-card"><div className="card-title"><div><h3>Weekly consistency</h3><p>Daily check-in completion</p></div><b className="lime-text">86%</b></div><div className="week-bars">{data.history.map((e,i)=><div key={e.date}><i style={{height:`${45+e.mood*5}%`}}/><span>{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></div><div className="card page-card insight-card"><Sparkles/><h3>Best pattern this week</h3><p>On days you sleep over 7 hours, your reported energy is 22% higher.</p><button onClick={notify}>Save insight <ChevronRight size={15}/></button></div></section>
    </>}
    {active==='Journal'&&<section className="wide-grid"><div className="card page-card journal-compose"><h3>How did today feel?</h3><p>Capture a thought before it slips away.</p><textarea placeholder="Write without overthinking it…" defaultValue={data.today.notes}/><button className="primary" onClick={notify}>Save reflection</button></div><div className="card page-card timeline"><h3>Recent reflections</h3>{['A focused day with steady energy.','Proud that I trained even when motivation was low.','More water made the afternoon feel easier.'].map((text,i)=><div key={text}><span>{29-i}<small>JUN</small></span><p>{text}</p></div>)}</div></section>}
    {active==='Progress'&&<><section className="card page-card progress-chart"><div className="card-title"><div><h3>Weight progression</h3><p>Seven-day trend</p></div><span className="down"><TrendingDown size={15}/> 0.6 kg</span></div><ResponsiveContainer width="100%" height={280}><AreaChart data={data.history}><defs><linearGradient id="bigWeight" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8ff4f" stopOpacity=".3"/><stop offset="1" stopColor="#d8ff4f" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:'#747d86',fontSize:10}}/><Tooltip contentStyle={{background:'#151a20',border:'1px solid #30363d',borderRadius:10}}/><Area type="monotone" dataKey="weight" stroke="#d8ff4f" strokeWidth={3} fill="url(#bigWeight)"/></AreaChart></ResponsiveContainer></section><section className="milestone-grid">{[['7 days','Current streak',Flame,'#f7c76c'],['4 / 5','Weekly workouts',Dumbbell,'#6fe2c1'],['92%','Goal consistency',Target,'#d8ff4f']].map(([value,label,Icon,color]:any)=><div className="card milestone" key={label}><Icon style={{color}}/><b>{value}</b><span>{label}</span></div>)}</section></>}
    {active==='Goals'&&<>{showGoalForm&&<section className="card new-goal-form"><label>Goal title<input placeholder="e.g. Run a 10K" value={goalDraft.title} onChange={e=>setGoalDraft(g=>({...g,title:e.target.value}))}/></label><label>Target<input type="number" min="1" value={goalDraft.target} onChange={e=>setGoalDraft(g=>({...g,target:Number(e.target.value)}))}/></label><label>Unit<input placeholder="times, km, hours…" value={goalDraft.unit} onChange={e=>setGoalDraft(g=>({...g,unit:e.target.value}))}/></label><label>Due date<input type="date" value={goalDraft.dueDate} onChange={e=>setGoalDraft(g=>({...g,dueDate:e.target.value}))}/></label><button className="primary" onClick={addGoal}><Check size={17}/>Save goal</button></section>}<section className="goals-page">{data.goals.map((g,i)=><motion.div className="card goal-card" whileHover={{y:-3}} key={g.id}><div className="goal-top"><span style={{background:`${g.color}18`,color:g.color}}>{i===0?<Footprints/>:i===1?<Dumbbell/>:<Moon/>}</span><button><MoreHorizontal/></button></div><h3>{g.title}</h3><p>{i===0?'Build a more active everyday baseline.':i===1?'Fuel recovery and muscle growth.':'Protect energy and focus tomorrow.'}</p><div className="goal-numbers"><b>{g.progress.toLocaleString()}</b><span>/ {g.target.toLocaleString()}</span><em>{Math.round(g.progress/g.target*100)}%</em></div><Progress value={g.progress/g.target*100} color={g.color}/><small>+{20+i*10} XP when completed</small></motion.div>)}{preferences.customGoals.map(g=><motion.div className="card goal-card custom" whileHover={{y:-3}} key={g.id}><div className="goal-top"><span><Target/></span><button aria-label={`Delete ${g.title}`} onClick={()=>savePreferences({...preferences,customGoals:preferences.customGoals.filter(x=>x.id!==g.id)})}><X size={17}/></button></div><h3>{g.title}</h3><p>{g.dueDate?`Due ${g.dueDate}`:'Personal goal · no deadline'}</p><div className="goal-numbers"><b>{g.progress}</b><span>/ {g.target} {g.unit}</span><em>{Math.round(g.progress/g.target*100)}%</em></div><Progress value={g.progress/g.target*100}/><small>Saved to your profile</small></motion.div>)}</section></>}
    {active==='Settings'&&<section className="settings-grid"><div className="card settings-card"><h3>Preferences</h3><p>Control your daily experience.</p>{([['notifications','Daily notifications','Reminders at 10:00, 17:00 and 22:00',Bell],['weekly','Weekly summary','A recap every Sunday evening',CalendarDays],['penalties','Penalty system','Deduct coins for missed commitments',TrendingDown],['dark','Dark appearance','Easy on the eyes, day and night',Moon]] as const).map(([key,label,sub,Icon])=><button className="setting-row" key={key} onClick={()=>toggle(key)}><span className="setting-icon"><Icon size={18}/></span><span><b>{label}</b><small>{sub}</small></span><i className={settings[key]?'switch on':'switch'}><em/></i></button>)}</div><div className="card settings-card"><h3>Your daily goals</h3><p>These targets are saved to your profile.</p>{([['calories','Calorie goal','kcal'],['protein','Protein goal','g'],['water','Water goal','L'],['steps','Step goal','steps']] as const).map(([key,label,unit])=><label className="target-row" key={key}><span>{label}</span><div><input aria-label={label} type="number" step={key==='water'?0.1:1} value={targets[key]} onChange={e=>setTargets(t=>({...t,[key]:Number(e.target.value)}))}/><small>{unit}</small></div></label>)}<button className="primary" onClick={persist}><Check size={17}/>Save goals & preferences</button></div></section>}
    {active==='Profile'&&<section className="profile-layout"><div className="card profile-summary"><div className="profile-avatar">{(profile.name||data.user.name).split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><h2>{profile.name||data.user.name}</h2><p>{profile.email||'Add your email'}</p><div><span><b>{data.user.level}</b>Level</span><span><b>{data.user.xp.toLocaleString()}</b>Total XP</span><span><b>{data.user.streak}</b>Day streak</span></div></div><div className="card settings-card profile-form"><h3>Personal information</h3><p>This is your profile—make it yours.</p><div className="profile-fields"><label>Full name<input value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>Email<input type="email" value={profile.email} onChange={e=>setProfile(p=>({...p,email:e.target.value}))}/></label><label>Age<input type="number" value={profile.age} onChange={e=>setProfile(p=>({...p,age:e.target.value}))}/></label><label>Height<input placeholder="e.g. 178 cm" value={profile.height} onChange={e=>setProfile(p=>({...p,height:e.target.value}))}/></label><label>Current weight<input placeholder="e.g. 74 kg" value={profile.weight} onChange={e=>setProfile(p=>({...p,weight:e.target.value}))}/></label></div><button className="primary" onClick={persist}><Check size={17}/>Save my profile</button></div></section>}
  </motion.div>
}

function OnboardingModal({initial,complete}:{initial:Preferences;complete:(p:Preferences)=>void}){
  const [step,setStep]=useState(1);
  const [profile,setProfile]=useState(initial.profile);
  const [targets,setTargets]=useState(initial.targets);
  const finish=()=>complete({...initial,profile,targets,onboardingComplete:true});
  return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}}/><motion.div className="modal onboarding" initial={{opacity:0,y:25,scale:.97}} animate={{opacity:1,y:0,scale:1}}>
    <div className="onboarding-progress"><i className="active"/><i className={step===2?'active':''}/></div>
    {step===1?<><p className="eyebrow">WELCOME TO DAYLIGHT</p><h2>Let’s make this yours.</h2><p className="onboarding-copy">Tell us a little about you. You can change this anytime from Profile.</p><div className="profile-fields onboarding-fields"><label>Your name<input autoFocus placeholder="Your name" value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>Email<input type="email" placeholder="you@example.com" value={profile.email} onChange={e=>setProfile(p=>({...p,email:e.target.value}))}/></label><label>Age<input type="number" placeholder="Age" value={profile.age} onChange={e=>setProfile(p=>({...p,age:e.target.value}))}/></label><label>Height<input placeholder="e.g. 178 cm" value={profile.height} onChange={e=>setProfile(p=>({...p,height:e.target.value}))}/></label><label>Current weight<input placeholder="e.g. 74 kg" value={profile.weight} onChange={e=>setProfile(p=>({...p,weight:e.target.value}))}/></label></div><div className="modal-actions"><button className="primary" disabled={!profile.name.trim()} onClick={()=>setStep(2)}>Set my goals <ChevronRight size={17}/></button></div></>:<><p className="eyebrow">YOUR DAILY TARGETS</p><h2>What are you aiming for?</h2><p className="onboarding-copy">These shape your dashboard progress. Start realistic—you can adjust them later.</p><div className="onboarding-targets">{([['calories','Calories','kcal'],['protein','Protein','g'],['water','Water','L'],['steps','Steps','steps']] as const).map(([key,label,unit])=><label key={key}><span>{label}</span><div><input aria-label={`${label} goal`} type="number" step={key==='water'?0.1:1} value={targets[key]} onChange={e=>setTargets(t=>({...t,[key]:Number(e.target.value)}))}/><small>{unit}</small></div></label>)}</div><div className="modal-actions onboarding-actions"><button onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={finish}><Check size={17}/>Start tracking</button></div></>}
  </motion.div></>
}

function NotificationPanel({items,close}:{items:DashboardData['notifications'];close:()=>void}){return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.aside className="notification-panel" initial={{x:420}} animate={{x:0}} exit={{x:420}} transition={{type:'spring',damping:28}}><div className="panel-head"><div><p>INBOX</p><h2>Notifications</h2></div><button onClick={close}><X/></button></div><div className="schedule-box"><Bell size={18}/><div><b>Your daily rhythm</b><span>Reminders at 10:00 · 17:00 · 22:00</span></div></div>{items.map(n=><div className="notification" key={n.id}><span className={n.type}><Flame size={17}/></span><div><b>{n.title}</b><p>{n.message}</p><small>Just now</small></div></div>)}<div className="empty-note"><Check size={18}/><span>You’re all caught up.</span></div></motion.aside></>}

function LogModal({entry,close,save}:{entry:Entry;close:()=>void;save:(e:Entry)=>void}){const [form,setForm]=useState({...entry});const set=(k:keyof Entry,v:any)=>setForm(f=>({...f,[k]:v}));const metrics=useMemo(()=>[['calories','Calories','kcal'],['protein','Protein','g'],['water','Water','L'],['sleep','Sleep','hrs'],['steps','Steps',''],['weight','Weight','kg'],['workoutMinutes','Workout','min']] as const,[]);return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.div className="modal" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><div className="modal-head"><div><p>DAILY CHECK-IN</p><h2>Log your day</h2><span>Small inputs. Meaningful progress.</span></div><button onClick={close}><X/></button></div><div className="metric-form">{metrics.map(([key,label,unit])=><label key={key}><span>{label}</span><div><input type="number" step="0.1" value={form[key] as number} onChange={e=>set(key,Number(e.target.value))}/><small>{unit}</small></div></label>)}</div><div className="sliders"><label><span>Mood <b>{form.mood}/10</b></span><input type="range" min="1" max="10" value={form.mood} onChange={e=>set('mood',Number(e.target.value))}/></label><label><span>Energy <b>{form.energy}/10</b></span><input type="range" min="1" max="10" value={form.energy} onChange={e=>set('energy',Number(e.target.value))}/></label></div><label className="notes"><span>Today’s reflection</span><textarea placeholder="What made today meaningful?" value={form.notes} onChange={e=>set('notes',e.target.value)}/></label><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(form)}><Check size={17}/> Save today</button></div></motion.div></>}
