import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { Activity, Apple, Bell, BookOpen, CalendarDays, Check, ChevronRight, Coins, Droplets, Dumbbell, Flame, Footprints, HeartPulse, Home, Image as ImageIcon, LayoutGrid, Menu, Moon, MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TrendingDown, Trophy, User, X, Zap } from 'lucide-react';
import type { CustomGoal, DashboardData, Entry, FoodAnalysis, Preferences } from './types';

const API='/api';
const defaultPreferences:Preferences={profile:{name:'',email:'',age:'',height:'',weight:''},targets:{calories:2200,protein:140,water:2.5,steps:10000},settings:{notifications:true,weekly:true,penalties:false,dark:true},customGoals:[],onboardingComplete:false};
const pageFromPath=()=>{const value=window.location.pathname.slice(1).toLowerCase();return ({overview:'Overview',journal:'Journal',progress:'Progress',goals:'Goals',settings:'Settings',profile:'Profile'} as Record<string,string>)[value]||'Today'};
const fallback:DashboardData={user:{name:'New user',xp:0,coins:0,level:1,nextLevelXp:100,streak:0},today:{date:new Date().toISOString().slice(0,10),weight:0,calories:0,protein:0,water:0,sleep:0,steps:0,mood:0,energy:0,stress:0,workoutMinutes:0,notes:'',habits:{}},history:[],notifications:[],goals:[],recentFoodLogs:[]};

const nav=[['Today',Home],['Overview',LayoutGrid],['Journal',BookOpen],['Progress',Activity],['Goals',Target]] as const;
const habitInfo:{key:string;title:string;sub:string;icon:any;color:string}[]=[
  {key:'water',title:'Hydration goal',sub:'Log water throughout the day',icon:Zap,color:'#63d9ff'},
  {key:'vegetables',title:'Fruits & veggies',sub:'Five colorful servings',icon:Apple,color:'#d8ff4f'},
  {key:'teeth',title:'Brush teeth',sub:'Morning & evening',icon:Sparkles,color:'#f7c76c'},
  {key:'hygiene',title:'Personal care',sub:'Daily routine',icon:HeartPulse,color:'#ff8d9e'},
  {key:'sleep',title:'Sleep on time',sub:'Before 11:30 PM',icon:Moon,color:'#a88bfa'},
  {key:'learn',title:'Learn something',sub:'At least 20 minutes',icon:BookOpen,color:'#6fe2c1'}
];

function Ring({value,color='#d8ff4f',size=80,children}:{value:number;color?:string;size?:number;children?:any}){return <div className="ring" style={{width:size,height:size,background:`conic-gradient(${color} ${Math.min(100,value)*3.6}deg,rgba(255,255,255,.07) 0)`}}><div>{children}</div></div>}
function Progress({value,color='#d8ff4f'}:{value:number;color?:string}){return <div className="progress"><motion.i initial={{width:0}} animate={{width:`${Math.min(100,value)}%`}} transition={{duration:.8}} style={{background:color}}/></div>}
function MiniStat({icon:Icon,label,value,sub,color}:{icon:any;label:string;value:string;sub:string;color:string}){return <motion.div className="mini-stat card" whileHover={{y:-3}}><div className="stat-icon" style={{color,background:`${color}18`}}><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></motion.div>}

export default function App(){
  const [data,setData]=useState<DashboardData>(fallback); const [active,setActive]=useState(pageFromPath); const [modal,setModal]=useState(false); const [foodModal,setFoodModal]=useState(false); const [waterModal,setWaterModal]=useState(false); const [bell,setBell]=useState(false); const [menu,setMenu]=useState(false); const [saved,setSaved]=useState(false); const [preferences,setPreferences]=useState<Preferences|null>(null);
  useEffect(()=>{const onBack=()=>setActive(pageFromPath());window.addEventListener('popstate',onBack);return()=>window.removeEventListener('popstate',onBack)},[]);
  useEffect(()=>{(async()=>{try{let token=localStorage.getItem('dlt-private-profile-v1')?localStorage.getItem('dlt-token'):null;if(!token){const visitorId=crypto.randomUUID();const a=await fetch(`${API}/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'New user',email:`${visitorId}@daylight.local`,password:crypto.randomUUID()})}).then(r=>r.json());token=a.token;localStorage.setItem('dlt-token',String(token));localStorage.setItem('dlt-private-profile-v1','true')}const headers={Authorization:`Bearer ${token!}`};const [d,p]=await Promise.all([fetch(`${API}/dashboard`,{headers}).then(r=>r.json()),fetch(`${API}/preferences`,{headers}).then(r=>r.json())]);setData({...d,user:{...d.user,name:p.profile?.name||d.user.name}});setPreferences({...defaultPreferences,...p})}catch{setPreferences(defaultPreferences)}})()},[]);
  const toggleHabit=(key:string)=>setData(d=>{const today={...d.today,habits:{...d.today.habits,[key]:!d.today.habits[key]}};fetch(`${API}/entries`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify(today)}).catch(()=>{});return {...d,today}});
  const done=Object.values(data.today.habits||{}).filter(Boolean).length; const habitPct=Math.round(done/habitInfo.length*100);
  const targets=(preferences||defaultPreferences).targets;
  const chart=data.history.filter(x=>x.weight>0).slice(-7).map(x=>({...x,day:new Date(`${x.date}T12:00:00`).toLocaleDateString('en',{weekday:'short'}).slice(0,1)}));
  const dashboardGoals=[
    {id:1,title:'Daily steps',progress:data.today.steps,target:targets.steps,color:'#d8ff4f',unit:'steps'},
    {id:2,title:'Protein',progress:data.today.protein,target:targets.protein,color:'#6fe2c1',unit:'g'},
    {id:3,title:'Water',progress:data.today.water,target:targets.water,color:'#63d9ff',unit:'L'},
    {id:4,title:'Calories',progress:data.today.calories,target:targets.calories,color:'#f7c76c',unit:'kcal'}
  ];
  const todayMeals=data.recentFoodLogs.filter(log=>log.entryDate===data.today.date);
  const yesterday=data.history.filter(entry=>entry.date<data.today.date).at(-1);
  const yesterdayMeals=yesterday?data.recentFoodLogs.filter(log=>log.entryDate===yesterday.date):[];
  const saveEntry=async(entry:Entry)=>{setData(d=>({...d,today:entry,history:d.history.some(x=>x.date===entry.date)?d.history.map(x=>x.date===entry.date?entry:x):[...d.history,entry]}));setModal(false);setSaved(true);setTimeout(()=>setSaved(false),2400);try{await fetch(`${API}/entries`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify(entry)})}catch{}};
  const showSaved=()=>{setSaved(true);setTimeout(()=>setSaved(false),2400)};
  const savePreferences=async(next:Preferences)=>{setPreferences(next);if(next.profile.name)setData(d=>({...d,user:{...d.user,name:next.profile.name}}));showSaved();try{await fetch(`${API}/preferences`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify(next)})}catch{}};
  const loginAccount=async(email:string,password:string)=>{const response=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not sign in');localStorage.setItem('dlt-token',body.token);localStorage.setItem('dlt-private-profile-v1','true');window.location.reload()};
  const go=(page:string)=>{setActive(page);setMenu(false);const path=page==='Today'?'/':`/${page.toLowerCase()}`;if(window.location.pathname!==path)window.history.pushState({},'',path);window.scrollTo({top:0,behavior:'smooth'})};
  return <div className="app-shell">
    <aside className={menu?'sidebar open':'sidebar'}><div className="brand" onClick={()=>go('Today')}><div className="brand-mark"><Check size={18}/></div><b>daylight</b><button className="mobile-x" onClick={(e)=>{e.stopPropagation();setMenu(false)}}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>go(n)}><I size={19}/><span>{n}</span>{active===n&&<i/>}</button>)}</nav><div className="sidebar-bottom"><div className="upgrade"><Sparkles size={20}/><b>Unlock your best</b><p>Go Pro for deeper insights.</p><button onClick={()=>go('Settings')}>Explore Daylight Pro</button></div><button className={active==='Settings'?'active':''} onClick={()=>go('Settings')}><Settings size={19}/>Settings</button><button className={active==='Profile'?'active':''} onClick={()=>go('Profile')}><User size={19}/>Profile</button></div></aside>
    <main>
      <header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Search your day..."/><kbd>⌘ K</kbd></div><div className="header-actions"><div className="streak-pill"><Flame size={17}/><b>{data.user.streak}</b><span>day streak</span></div><button className="icon-btn" aria-label="Notifications" onClick={()=>setBell(!bell)}><Bell size={20}/><i/></button><button className="avatar" aria-label="Open profile" onClick={()=>go('Profile')}>AM</button></div></header>
      <div className="content">
        {active==='Today'?<>
        <section className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>Hello, <em>{data.user.name.split(' ')[0]}.</em></h1><p>Everything below comes from what you log.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={19}/> Log today</button></section>
        <section className="level card"><div className="level-badge"><Trophy size={22}/><b>{data.user.level}</b></div><div className="level-copy"><div><b>Level {data.user.level}</b><span>{data.user.xp.toLocaleString()} / {data.user.nextLevelXp.toLocaleString()} XP</span></div><Progress value={data.user.xp/data.user.nextLevelXp*100}/><small><Zap size={13}/>Activity is added only when you log it</small></div><div className="coin-box"><Coins size={20}/><div><b>{data.user.coins}</b><span>coins</span></div></div></section>
        <section className="section-head"><div><h2>Today at a glance</h2><p>Your key metrics, all in one place.</p></div><button onClick={()=>go('Overview')}>View details <ChevronRight size={15}/></button></section>
        <section className="stats-grid"><MiniStat icon={Footprints} label="Steps" value={data.today.steps.toLocaleString()} sub={`${Math.round(data.today.steps/Math.max(1,targets.steps)*100)}% of your goal`} color="#d8ff4f"/><MiniStat icon={Dumbbell} label="Active time" value={`${data.today.workoutMinutes} min`} sub={data.today.workoutMinutes?'Logged today':'Nothing logged yet'} color="#6fe2c1"/><MiniStat icon={Moon} label="Sleep" value={data.today.sleep?`${data.today.sleep} hrs`:'—'} sub={data.today.sleep?'Logged today':'Nothing logged yet'} color="#a88bfa"/><MiniStat icon={HeartPulse} label="Mood" value={data.today.mood?`${data.today.mood}/10`:'—'} sub={data.today.mood?'Logged today':'Nothing logged yet'} color="#ff8d9e"/></section>
        <section className="main-grid">
          <div className="left-column">
            <div className="card nutrition"><div className="card-title"><div><h3>Daily fuel</h3><p>Only food and water you log appear here</p></div></div><div className="nutrition-body"><Ring value={data.today.calories/Math.max(1,targets.calories)*100} size={134}><b>{data.today.calories.toLocaleString()}</b><span>of {targets.calories.toLocaleString()} kcal</span></Ring><div className="macros"><div><span><i style={{background:'#d8ff4f'}}/>Protein <b>{data.today.protein} / {targets.protein}g</b></span><Progress value={data.today.protein/Math.max(1,targets.protein)*100}/></div><div><span><i style={{background:'#63d9ff'}}/>Water <b>{data.today.water} / {targets.water}L</b></span><Progress value={data.today.water/Math.max(.1,targets.water)*100} color="#63d9ff"/></div><div className="fuel-actions"><button className="primary" onClick={()=>setFoodModal(true)}><ImageIcon size={17}/>Add food</button><button onClick={()=>setWaterModal(true)}><Droplets size={17}/>Add water</button></div></div></div></div>
            <div className="card meal-history"><div className="card-title"><div><h3>Today’s meals</h3><p>Saved to your account</p></div><b>{todayMeals.length}</b></div>{todayMeals.length?<div className="meal-list">{todayMeals.map(meal=><div key={meal.id}><span><b>{meal.foodName}</b><small>{new Date(meal.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></span><span><b>{meal.calories} kcal</b><small>{meal.protein}g protein</small></span></div>)}</div>:<div className="empty-state small">No meals logged today.</div>}</div>
            <div className="card habits"><div className="card-title"><div><h3>Daily rhythm</h3><p>{done} of {habitInfo.length} habits completed</p></div><Ring value={habitPct} size={52}><b>{habitPct}%</b></Ring></div><div className="habit-list">{habitInfo.map(({key,title,sub,icon:Icon,color})=><motion.button whileTap={{scale:.98}} key={key} onClick={()=>toggleHabit(key)} className={data.today.habits?.[key]?'done':''}><span className="habit-icon" style={{color,background:`${color}13`}}><Icon size={18}/></span><span><b>{title}</b><small>{sub}</small></span><i>{data.today.habits?.[key]&&<Check size={15}/>}</i></motion.button>)}</div></div>
          </div>
          <div className="right-column">
            <div className="card weight"><div className="card-title"><div><h3>Weight trend</h3><p>Your logged weights</p></div></div>{chart.length?<><div className="weight-value"><b>{chart.at(-1)?.weight}</b><span>kg</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:4,right:4,top:8,bottom:0}}><defs><linearGradient id="weight" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8ff4f" stopOpacity=".28"/><stop offset="1" stopColor="#d8ff4f" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#6f7781',fontSize:11}}/><Tooltip contentStyle={{background:'#151a20',border:'1px solid #30363d',borderRadius:10}}/><Area type="monotone" dataKey="weight" stroke="#d8ff4f" strokeWidth={2.5} fill="url(#weight)"/></AreaChart></ResponsiveContainer></div></>:<div className="empty-state">Log your weight to start a trend.</div>}</div>
            <div className="card goals"><div className="card-title"><div><h3>Today’s goals</h3><p>Updates when you change Settings</p></div><button aria-label="Open settings" onClick={()=>go('Settings')}><Settings size={18}/></button></div>{dashboardGoals.map(g=><div className="goal" key={g.id}><div><span>{g.title}</span><b>{Math.round(g.progress/Math.max(.1,g.target)*100)}%</b></div><Progress value={g.progress/Math.max(.1,g.target)*100} color={g.color}/><small>{g.progress.toLocaleString()} of {g.target.toLocaleString()} {g.unit}</small></div>)}</div>
            <div className="card yesterday-card"><div className="card-title"><div><h3>Yesterday</h3><p>{yesterday?.date||'No previous entry yet'}</p></div></div>{yesterday?<><div className="yesterday-stats"><span><b>{yesterday.calories}</b>kcal</span><span><b>{yesterday.protein}g</b>protein</span><span><b>{yesterday.water}L</b>water</span><span><b>{yesterday.steps}</b>steps</span></div>{yesterday.notes&&<p className="yesterday-note">“{yesterday.notes}”</p>}{yesterdayMeals.length>0&&<small>{yesterdayMeals.length} saved meal{yesterdayMeals.length===1?'':'s'}</small>}</>:<div className="empty-state small">Tomorrow, today’s results will appear here.</div>}</div>
            <div className="card reflection"><div className="quote">“</div><h3>One thought for today</h3><p>What’s one thing you did today that your future self will thank you for?</p><button onClick={()=>setModal(true)}>Write a reflection <ChevronRight size={16}/></button></div>
          </div>
        </section>
        </>:<FeaturePage active={active} data={data} preferences={preferences||defaultPreferences} savePreferences={savePreferences} openLog={()=>setModal(true)} notify={showSaved}/>} 
      </div>
      <nav className="mobile-nav">{nav.slice(0,4).map(([n,I])=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I size={20}/><span>{n}</span></button>)}<button onClick={()=>setMenu(true)}><Menu size={20}/><span>More</span></button></nav>
    </main>
    <AnimatePresence>{bell&&<NotificationPanel items={data.notifications} close={()=>setBell(false)}/>}</AnimatePresence>
    <AnimatePresence>{modal&&<LogModal entry={data.today} close={()=>setModal(false)} save={saveEntry}/>}</AnimatePresence>
    <AnimatePresence>{foodModal&&<FoodModal close={()=>setFoodModal(false)} logged={(entry,log)=>{setData(d=>({...d,today:entry,recentFoodLogs:[{...log,entryDate:entry.date},...d.recentFoodLogs]}));setFoodModal(false);showSaved()}}/>}</AnimatePresence>
    <AnimatePresence>{waterModal&&<WaterModal close={()=>setWaterModal(false)} logged={entry=>{setData(d=>({...d,today:entry}));setWaterModal(false);showSaved()}}/>}</AnimatePresence>
    <AnimatePresence>{preferences&&!preferences.onboardingComplete&&<OnboardingModal initial={preferences} complete={savePreferences} login={loginAccount}/>}</AnimatePresence>
    <AnimatePresence>{saved&&<motion.div className="toast" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}}><span><Check size={16}/></span><div><b>Changes saved</b><small>Your updates are safely recorded.</small></div></motion.div>}</AnimatePresence>
  </div>
}

function FeaturePage({active,data,preferences,savePreferences,openLog,notify}:{active:string;data:DashboardData;preferences:Preferences;savePreferences:(p:Preferences)=>void;openLog:()=>void;notify:()=>void}){
  const [settings,setSettings]=useState(preferences.settings);
  const [targets,setTargets]=useState(preferences.targets);
  const [profile,setProfile]=useState(preferences.profile);
  const [accountPassword,setAccountPassword]=useState('');
  const [accountError,setAccountError]=useState('');
  const [showGoalForm,setShowGoalForm]=useState(false);
  const [goalDraft,setGoalDraft]=useState({title:'',target:1,unit:'times',dueDate:''});
  const toggle=(key:keyof typeof settings)=>setSettings(s=>({...s,[key]:!s[key]}));
  const persist=()=>savePreferences({...preferences,settings,targets,profile});
  const secureAccount=async()=>{setAccountError('');try{const response=await fetch(`${API}/account`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify({name:profile.name,email:profile.email,password:accountPassword})});const body=await response.json();if(!response.ok)throw new Error(body.error);localStorage.setItem('dlt-token',body.token);savePreferences({...preferences,settings,targets,profile});setAccountPassword('');notify()}catch(error:any){setAccountError(error.message||'Could not secure this account.')}};
  const addGoal=()=>{if(!goalDraft.title.trim())return;const goal:CustomGoal={id:crypto.randomUUID(),title:goalDraft.title.trim(),target:Number(goalDraft.target)||1,progress:0,unit:goalDraft.unit||'times',dueDate:goalDraft.dueDate,completed:false};savePreferences({...preferences,settings,targets,profile,customGoals:[...preferences.customGoals,goal]});setGoalDraft({title:'',target:1,unit:'times',dueDate:''});setShowGoalForm(false)};
  const pageIntro:Record<string,[string,string]>={
    Overview:['Your overview','The bigger picture across health, habits, and momentum.'],
    Journal:['Journal','A quiet place to reflect, notice patterns, and reset.'],
    Progress:['Your progress','Small choices, compounding in the right direction.'],
    Goals:['Goals','Turn intention into a plan you can actually finish.'],
    Settings:['Settings','Make Daylight work the way you do.'],
    Profile:['Your profile','Manage your identity and personal targets.']
  };
  const [title,subtitle]=pageIntro[active]||['Daylight','Your life, in focus.'];
  const average=(key:keyof Entry)=>Math.round(data.history.reduce((sum,e)=>sum+Number(e[key]||0),0)/Math.max(1,data.history.length)*10)/10;
  return <motion.div className="feature-page" key={active} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>
    <section className="page-hero"><div><p className="eyebrow">DAYLIGHT / {active.toUpperCase()}</p><h1>{title}</h1><p>{subtitle}</p></div>{active==='Journal'&&<button className="primary" onClick={openLog}><Plus size={18}/>New entry</button>}{active==='Goals'&&<button className="primary" onClick={()=>setShowGoalForm(v=>!v)}><Plus size={18}/>Add goal</button>}</section>
    {active==='Overview'&&<>
      <section className="stats-grid page-stats"><MiniStat icon={Footprints} label="Average steps" value={data.history.length?average('steps').toLocaleString():'—'} sub="Your logged days" color="#d8ff4f"/><MiniStat icon={Moon} label="Average sleep" value={data.history.length?`${average('sleep')} hrs`:'—'} sub="Your logged days" color="#a88bfa"/><MiniStat icon={HeartPulse} label="Average mood" value={data.history.length?`${average('mood')}/10`:'—'} sub="Your logged days" color="#ff8d9e"/><MiniStat icon={Dumbbell} label="Active minutes" value={data.history.length?average('workoutMinutes').toLocaleString():'—'} sub="Your logged days" color="#6fe2c1"/></section>
      <section className="card page-card"><div className="card-title"><div><h3>Your logged days</h3><p>No generated insights or sample records</p></div><b className="lime-text">{data.history.length}</b></div>{data.history.length?<div className="week-bars">{data.history.slice(-7).map(e=><div key={e.date}><i style={{height:`${Math.max(10,Math.min(100,e.mood*10))}%`}}/><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('en',{weekday:'short'}).slice(0,1)}</span></div>)}</div>:<div className="empty-state">Log your first day to see an overview.</div>}</section>
    </>}
    {active==='Journal'&&<section className="wide-grid"><div className="card page-card journal-compose"><h3>Today’s reflection</h3><p>Your journal contains only what you write.</p><textarea placeholder="Write without overthinking it…" value={data.today.notes} readOnly/><button className="primary" onClick={openLog}>Edit today’s entry</button></div><div className="card page-card timeline"><h3>Recent reflections</h3>{data.history.filter(e=>e.notes.trim()).slice(-5).reverse().map(e=><div key={e.date}><span>{new Date(`${e.date}T12:00:00`).getDate()}<small>{new Date(`${e.date}T12:00:00`).toLocaleDateString('en',{month:'short'}).toUpperCase()}</small></span><p>{e.notes}</p></div>)}{!data.history.some(e=>e.notes.trim())&&<div className="empty-state">No reflections logged yet.</div>}</div></section>}
    {active==='Progress'&&<section className="card page-card progress-chart"><div className="card-title"><div><h3>Weight progression</h3><p>Only your logged weights</p></div></div>{data.history.some(e=>e.weight>0)?<ResponsiveContainer width="100%" height={280}><AreaChart data={data.history.filter(e=>e.weight>0)}><defs><linearGradient id="bigWeight" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8ff4f" stopOpacity=".3"/><stop offset="1" stopColor="#d8ff4f" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:'#747d86',fontSize:10}}/><Tooltip contentStyle={{background:'#151a20',border:'1px solid #30363d',borderRadius:10}}/><Area type="monotone" dataKey="weight" stroke="#d8ff4f" strokeWidth={3} fill="url(#bigWeight)"/></AreaChart></ResponsiveContainer>:<div className="empty-state">No weight entries yet.</div>}</section>}
    {active==='Goals'&&<>{showGoalForm&&<section className="card new-goal-form"><label>Goal title<input placeholder="e.g. Run a 10K" value={goalDraft.title} onChange={e=>setGoalDraft(g=>({...g,title:e.target.value}))}/></label><label>Target<input type="number" min="1" value={goalDraft.target} onChange={e=>setGoalDraft(g=>({...g,target:Number(e.target.value)}))}/></label><label>Unit<input placeholder="times, km, hours…" value={goalDraft.unit} onChange={e=>setGoalDraft(g=>({...g,unit:e.target.value}))}/></label><label>Due date<input type="date" value={goalDraft.dueDate} onChange={e=>setGoalDraft(g=>({...g,dueDate:e.target.value}))}/></label><button className="primary" onClick={addGoal}><Check size={17}/>Save goal</button></section>}<section className="goals-page">{data.goals.map((g,i)=><motion.div className="card goal-card" whileHover={{y:-3}} key={g.id}><div className="goal-top"><span style={{background:`${g.color}18`,color:g.color}}>{i===0?<Footprints/>:i===1?<Dumbbell/>:<Moon/>}</span><button><MoreHorizontal/></button></div><h3>{g.title}</h3><p>{i===0?'Build a more active everyday baseline.':i===1?'Fuel recovery and muscle growth.':'Protect energy and focus tomorrow.'}</p><div className="goal-numbers"><b>{g.progress.toLocaleString()}</b><span>/ {g.target.toLocaleString()}</span><em>{Math.round(g.progress/g.target*100)}%</em></div><Progress value={g.progress/g.target*100} color={g.color}/><small>+{20+i*10} XP when completed</small></motion.div>)}{preferences.customGoals.map(g=><motion.div className="card goal-card custom" whileHover={{y:-3}} key={g.id}><div className="goal-top"><span><Target/></span><button aria-label={`Delete ${g.title}`} onClick={()=>savePreferences({...preferences,customGoals:preferences.customGoals.filter(x=>x.id!==g.id)})}><X size={17}/></button></div><h3>{g.title}</h3><p>{g.dueDate?`Due ${g.dueDate}`:'Personal goal · no deadline'}</p><div className="goal-numbers"><b>{g.progress}</b><span>/ {g.target} {g.unit}</span><em>{Math.round(g.progress/g.target*100)}%</em></div><Progress value={g.progress/g.target*100}/><small>Saved to your profile</small></motion.div>)}</section></>}
    {active==='Settings'&&<section className="settings-grid"><div className="card settings-card"><h3>Preferences</h3><p>Control your daily experience.</p>{([['notifications','Daily notifications','Reminders at 10:00, 17:00 and 22:00',Bell],['weekly','Weekly summary','A recap every Sunday evening',CalendarDays],['penalties','Penalty system','Deduct coins for missed commitments',TrendingDown],['dark','Dark appearance','Easy on the eyes, day and night',Moon]] as const).map(([key,label,sub,Icon])=><button className="setting-row" key={key} onClick={()=>toggle(key)}><span className="setting-icon"><Icon size={18}/></span><span><b>{label}</b><small>{sub}</small></span><i className={settings[key]?'switch on':'switch'}><em/></i></button>)}</div><div className="card settings-card"><h3>Your daily goals</h3><p>These targets are saved to your profile.</p>{([['calories','Calorie goal','kcal'],['protein','Protein goal','g'],['water','Water goal','L'],['steps','Step goal','steps']] as const).map(([key,label,unit])=><label className="target-row" key={key}><span>{label}</span><div><input aria-label={label} type="number" step={key==='water'?0.1:1} value={targets[key]} onChange={e=>setTargets(t=>({...t,[key]:Number(e.target.value)}))}/><small>{unit}</small></div></label>)}<button className="primary" onClick={persist}><Check size={17}/>Save goals & preferences</button></div></section>}
    {active==='Profile'&&<section className="profile-layout"><div className="card profile-summary"><div className="profile-avatar">{(profile.name||data.user.name).split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><h2>{profile.name||data.user.name}</h2><p>{profile.email||'Add your email'}</p><div><span><b>{data.user.level}</b>Level</span><span><b>{data.user.xp.toLocaleString()}</b>Total XP</span><span><b>{data.user.streak}</b>Day streak</span></div></div><div className="card settings-card profile-form"><h3>Personal information</h3><p>This is your profile—make it yours.</p><div className="profile-fields"><label>Full name<input value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>Email<input type="email" value={profile.email} onChange={e=>setProfile(p=>({...p,email:e.target.value}))}/></label><label>Age<input type="number" value={profile.age} onChange={e=>setProfile(p=>({...p,age:e.target.value}))}/></label><label>Height<input placeholder="e.g. 178 cm" value={profile.height} onChange={e=>setProfile(p=>({...p,height:e.target.value}))}/></label><label>Current weight<input placeholder="e.g. 74 kg" value={profile.weight} onChange={e=>setProfile(p=>({...p,weight:e.target.value}))}/></label></div><button className="primary" onClick={persist}><Check size={17}/>Save my profile</button></div><div className="card settings-card account-card"><h3>Sign in from any device</h3><p>Connect this exact profile—including your meals, goals, results, and journal—to an email and password.</p><label>Email<input type="email" value={profile.email} onChange={e=>setProfile(p=>({...p,email:e.target.value}))}/></label><label>Password<input type="password" minLength={8} placeholder="At least 8 characters" value={accountPassword} onChange={e=>setAccountPassword(e.target.value)}/></label>{accountError&&<p className="form-error">{accountError}</p>}<button className="primary" onClick={secureAccount}><Check size={17}/>Enable account login</button></div></section>}
  </motion.div>
}

function OnboardingModal({initial,complete,login}:{initial:Preferences;complete:(p:Preferences)=>void;login:(email:string,password:string)=>Promise<void>}){
  const [step,setStep]=useState(1);
  const [profile,setProfile]=useState(initial.profile);
  const [targets,setTargets]=useState(initial.targets);
  const [loginMode,setLoginMode]=useState(false);
  const [loginEmail,setLoginEmail]=useState('');
  const [loginPassword,setLoginPassword]=useState('');
  const [loginError,setLoginError]=useState('');
  const submitLogin=async()=>{setLoginError('');try{await login(loginEmail,loginPassword)}catch(error:any){setLoginError(error.message||'Could not sign in')}};
  const finish=()=>complete({...initial,profile,targets,onboardingComplete:true});
  if(loginMode)return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}}/><motion.div className="modal onboarding login-modal" initial={{opacity:0,y:25,scale:.97}} animate={{opacity:1,y:0,scale:1}}><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your tracker.</h2><p className="onboarding-copy">Your meals, daily results, goals, and journal will load together.</p><div className="login-fields"><label>Email<input type="email" autoFocus value={loginEmail} onChange={e=>setLoginEmail(e.target.value)}/></label><label>Password<input type="password" value={loginPassword} onChange={e=>setLoginPassword(e.target.value)}/></label></div>{loginError&&<p className="form-error">{loginError}</p>}<div className="modal-actions onboarding-actions"><button onClick={()=>setLoginMode(false)}>Back</button><button className="primary" onClick={submitLogin}>Sign in</button></div></motion.div></>;
  return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}}/><motion.div className="modal onboarding" initial={{opacity:0,y:25,scale:.97}} animate={{opacity:1,y:0,scale:1}}>
    <div className="onboarding-progress"><i className="active"/><i className={step===2?'active':''}/></div>
    {step===1?<><p className="eyebrow">WELCOME TO DAYLIGHT</p><h2>Let’s make this yours.</h2><p className="onboarding-copy">Tell us a little about you. You can change this anytime from Profile.</p><div className="profile-fields onboarding-fields"><label>Your name<input autoFocus placeholder="Your name" value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>Email<input type="email" placeholder="you@example.com" value={profile.email} onChange={e=>setProfile(p=>({...p,email:e.target.value}))}/></label><label>Age<input type="number" placeholder="Age" value={profile.age} onChange={e=>setProfile(p=>({...p,age:e.target.value}))}/></label><label>Height<input placeholder="e.g. 178 cm" value={profile.height} onChange={e=>setProfile(p=>({...p,height:e.target.value}))}/></label><label>Current weight<input placeholder="e.g. 74 kg" value={profile.weight} onChange={e=>setProfile(p=>({...p,weight:e.target.value}))}/></label></div><div className="modal-actions onboarding-actions"><button onClick={()=>setLoginMode(true)}>Already have an account?</button><button className="primary" disabled={!profile.name.trim()} onClick={()=>setStep(2)}>Set my goals <ChevronRight size={17}/></button></div></>:<><p className="eyebrow">YOUR DAILY TARGETS</p><h2>What are you aiming for?</h2><p className="onboarding-copy">These shape your dashboard progress. Start realistic—you can adjust them later.</p><div className="onboarding-targets">{([['calories','Calories','kcal'],['protein','Protein','g'],['water','Water','L'],['steps','Steps','steps']] as const).map(([key,label,unit])=><label key={key}><span>{label}</span><div><input aria-label={`${label} goal`} type="number" step={key==='water'?0.1:1} value={targets[key]} onChange={e=>setTargets(t=>({...t,[key]:Number(e.target.value)}))}/><small>{unit}</small></div></label>)}</div><div className="modal-actions onboarding-actions"><button onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={finish}><Check size={17}/>Start tracking</button></div></>}
  </motion.div></>
}

function FoodModal({close,logged}:{close:()=>void;logged:(entry:Entry,log:DashboardData['recentFoodLogs'][number])=>void}){
  const [image,setImage]=useState('');
  const [description,setDescription]=useState('');
  const [result,setResult]=useState<FoodAnalysis>({foodName:'',calories:0,protein:0});
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const headers={'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`};
  const chooseImage=(file?:File)=>{if(!file)return;if(file.size>5_000_000){setError('Please choose an image under 5 MB.');return}const reader=new FileReader();reader.onload=()=>{setImage(String(reader.result));setResult({foodName:'',calories:0,protein:0});setError('')};reader.readAsDataURL(file)};
  const analyze=async()=>{setBusy(true);setError('');try{const response=await fetch(`${API}/food/analyze`,{method:'POST',headers,body:JSON.stringify({imageDataUrl:image,description})});const body=await response.json();if(!response.ok)throw new Error(body.error);setResult(body)}catch(e:any){setError(e.message||'Analysis failed. You can enter the values manually.')}finally{setBusy(false)}};
  const log=async()=>{setBusy(true);setError('');try{const response=await fetch(`${API}/food-logs`,{method:'POST',headers,body:JSON.stringify(result)});const body=await response.json();if(!response.ok)throw new Error(body.error);setImage('');logged(body.entry,body.log)}catch(e:any){setError(e.message||'Could not log this food.')}finally{setBusy(false)}};
  return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.div className="modal food-modal" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><div className="modal-head"><div><p>FOOD LOGGER</p><h2>Analyze or add food</h2><span>The photo is sent once to Google Gemini and is never stored.</span></div><button onClick={close}><X/></button></div><label className="food-upload">{image?<img src={image} alt="Food preview"/>:<><ImageIcon size={30}/><b>Add a food photo</b><span>JPEG, PNG or WebP · max 5 MB</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/></label><label className="notes"><span>Description (optional)</span><textarea placeholder="For example: grilled chicken, rice and salad" value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="analyze-button" disabled={busy||(!image&&!description)} onClick={analyze}><Sparkles size={17}/>{busy?'Analyzing…':'Analyze with AI'}</button><p className="estimate-note">AI nutrition values are estimates. Review and edit them before saving.</p><div className="food-result"><label>Food name<input value={result.foodName} onChange={e=>setResult(r=>({...r,foodName:e.target.value}))}/></label><label>Calories<input type="number" min="0" value={result.calories} onChange={e=>setResult(r=>({...r,calories:Number(e.target.value)}))}/></label><label>Protein (g)<input type="number" min="0" step="0.1" value={result.protein} onChange={e=>setResult(r=>({...r,protein:Number(e.target.value)}))}/></label></div>{result.notes&&<p className="analysis-notes">{result.notes} · {result.confidence} confidence</p>}{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" disabled={busy||!result.foodName.trim()} onClick={log}><Check size={17}/>Log food</button></div></motion.div></>
}

function WaterModal({close,logged}:{close:()=>void;logged:(entry:Entry)=>void}){
  const [milliliters,setMilliliters]=useState(250);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const add=async()=>{setBusy(true);setError('');try{const response=await fetch(`${API}/water`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('dlt-token')}`},body:JSON.stringify({liters:milliliters/1000})});const body=await response.json();if(!response.ok)throw new Error(body.error);logged(body.entry)}catch(e:any){setError(e.message||'Could not add water.')}finally{setBusy(false)}};
  return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.div className="modal water-modal" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><div className="modal-head"><div><p>HYDRATION</p><h2>Add water</h2><span>Choose an amount or enter your own.</span></div><button onClick={close}><X/></button></div><div className="water-presets">{[250,500,750].map(x=><button className={milliliters===x?'active':''} onClick={()=>setMilliliters(x)} key={x}><Droplets size={18}/>{x} ml</button>)}</div><label className="custom-water">Custom amount<div><input type="number" min="1" max="10000" value={milliliters} onChange={e=>setMilliliters(Number(e.target.value))}/><span>ml</span></div></label>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" disabled={busy||milliliters<=0} onClick={add}><Plus size={17}/>{busy?'Adding…':'Add water'}</button></div></motion.div></>
}

function NotificationPanel({items,close}:{items:DashboardData['notifications'];close:()=>void}){return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.aside className="notification-panel" initial={{x:420}} animate={{x:0}} exit={{x:420}} transition={{type:'spring',damping:28}}><div className="panel-head"><div><p>INBOX</p><h2>Notifications</h2></div><button onClick={close}><X/></button></div><div className="schedule-box"><Bell size={18}/><div><b>Your daily rhythm</b><span>Reminders at 10:00 · 17:00 · 22:00</span></div></div>{items.map(n=><div className="notification" key={n.id}><span className={n.type}><Flame size={17}/></span><div><b>{n.title}</b><p>{n.message}</p><small>Just now</small></div></div>)}<div className="empty-note"><Check size={18}/><span>You’re all caught up.</span></div></motion.aside></>}

function LogModal({entry,close,save}:{entry:Entry;close:()=>void;save:(e:Entry)=>void}){const [form,setForm]=useState({...entry});const set=(k:keyof Entry,v:any)=>setForm(f=>({...f,[k]:v}));const metrics=useMemo(()=>[['calories','Calories','kcal'],['protein','Protein','g'],['water','Water','L'],['sleep','Sleep','hrs'],['steps','Steps',''],['weight','Weight','kg'],['workoutMinutes','Workout','min']] as const,[]);return <><motion.div className="scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.div className="modal" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><div className="modal-head"><div><p>DAILY CHECK-IN</p><h2>Log your day</h2><span>Small inputs. Meaningful progress.</span></div><button onClick={close}><X/></button></div><div className="metric-form">{metrics.map(([key,label,unit])=><label key={key}><span>{label}</span><div><input type="number" step="0.1" value={form[key] as number} onChange={e=>set(key,Number(e.target.value))}/><small>{unit}</small></div></label>)}</div><div className="sliders"><label><span>Mood <b>{form.mood}/10</b></span><input type="range" min="1" max="10" value={form.mood} onChange={e=>set('mood',Number(e.target.value))}/></label><label><span>Energy <b>{form.energy}/10</b></span><input type="range" min="1" max="10" value={form.energy} onChange={e=>set('energy',Number(e.target.value))}/></label></div><label className="notes"><span>Today’s reflection</span><textarea placeholder="What made today meaningful?" value={form.notes} onChange={e=>set('notes',e.target.value)}/></label><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(form)}><Check size={17}/> Save today</button></div></motion.div></>}
